### ISSUE TITLE
Vim 8 package installation documentation/support

### ISSUE THREAD

**Issue by TamasBarta** [udalov/kotlin-vim#16]
I'm a noob with Vim package managers, but I noticed Vim 8 packages are not mentioned in README. What about them? Do you support them? How to install using that?

**Comment by udalov** [comment]
I'm not really familiar with any package managers except those listed in the ReadMe. FWIW, I don't use any package managers at all and am always installing the plugin manually on my machines. Doesn't the package manager you're using support a simple way to point it to the plugin sources on GitHub, so that it would download and install it on the first use, like the listed managers do? I honestly think it's not a goal of the ReadMe of this project to list every possible package manager out there.
